---
abstract: 'Retrieve frequency values and frequency-based lists from Brysbaert Subtitles Corpus'
author:
  - 'Roderick Garton <rgarton@cpan.org>'
build_requires:
  Array::Compare: '2.02'
  File::RandomLine: '0.20'
  File::Spec: '0.20'
  FindBin: '0'
  Lingua::Orthon: '0.01'
  Statistics::Lite: '3.2'
  Test::More: '0.92'
configure_requires:
  Lingua::Orthon: '0.01'
  Module::Build: '0.4007'
  Statistics::Lite: '3.2'
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Lingua-Norms-SUBTLEX
provides:
  Lingua::Norms::SUBTLEX:
    file: lib/Lingua/Norms/SUBTLEX.pm
    version: '0.01'
requires:
  Config: '0'
  File::RandomLine: '0.20'
  File::Spec: '0.20'
  Lingua::Orthon: '0.01'
  Statistics::Lite: '3.2'
  String::Util: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '0.01'
